'''
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
# 1 1 2 3 5 8 13 21 34
#     ^     ^        ^
# even numbers appear at every third position in the fibonacci series
MAX = 4000000
total = 0
a,b,c = 1,1,2
while c<MAX:
    total += c
    a = b+c
    b = c+a
    c = a+b
    
print total
